### PR TITLE
Add Default Community Health files

### PR DESCRIPTION
**Pull request by OPC-16**
Motive of this PR is to create default community health files like `code-of-conduct.md`, `governance.md`, etc. Please refer to [this issue](https://github.com/kubevirt/community/issues/235) and also see the discussion done in [this PR](https://github.com/kubevirt/project-infra/pull/3078).

### CODE REVIEW

**Comment by OPC-16** [comment]
Hey @dhiller, should I create single PR and add commits for all files in it or different PRs for individual files?

Also, please give suggestions wherever required.

**Comment by dhiller** [comment]
> Hey @dhiller, should I create single PR and add commits for all files in it or different PRs for individual files?
> 
> Also, please give suggestions wherever required.

I would say we can add them each in a single commit in this PR.

**Comment by OPC-16** [comment]
> I would say we can add them each in a single commit in this PR.

ok, I will try to push the changes tonight.

**Comment by OPC-16** [comment]
Hey @dhiller, Please have a look.

**Comment by dhiller** [comment]
> Hey @dhiller, Please have a look.

Thanks! Looks good so far. Do we also want to add the default pull request and issue templates with this PR?

**Comment by OPC-16** [comment]
> Do we also want to add the default pull request and issue templates with this PR?

yes, actually I had my exams. I'll add the templates tonight.

**Comment by OPC-16** [comment]
@dhiller I have added the templates. Please have a look.

**Comment by dhiller** [comment]
> > Do we also want to add the default pull request and issue templates with this PR?
> 
> yes, actually I had my exams. I'll add the templates tonight.

Oh, I hope all went well with these :crossed_fingers:

**Comment by OPC-16** [comment]
> Oh, I hope all went well with these 🤞

Quite good I guess 😁, thanks 🙏

**Comment by OPC-16** [comment]
Hey @dhiller are you back from New Year's celebration? 😅

**Comment by dhiller** [comment]
@OPC-16 thank you for your work! Looks great!

**Comment by OPC-16** [comment]
@dhiller Welcome :)

**Pull request merged**
